/* NZ Election 2026 — Compare the Parties
   Policy summaries are deliberately short and simplified for side-by-side
   comparison. They reflect each party's general, publicly stated direction
   and are NOT a substitute for reading official manifestos. */

const DOMAINS = [
  { id: "tax",       name: "Tax & Cost of Living" },
  { id: "housing",   name: "Housing & Rentals" },
  { id: "health",    name: "Health & Hospitals" },
  { id: "education", name: "Education & Schools" },
  { id: "climate",   name: "Climate & Environment" },
  { id: "energy",    name: "Energy & Resources" },
  { id: "immigration", name: "Immigration" },
  { id: "justice",   name: "Law & Order" },
  { id: "welfare",   name: "Welfare & Social Security" },
  { id: "treaty",    name: "Maori / Te Tiriti" },
  { id: "transport", name: "Transport & Infrastructure" },
  { id: "foreign",   name: "Foreign Policy & Defence" },
  { id: "agriculture", name: "Agriculture & Primary Industries" },
  { id: "democracy", name: "Democracy & Constitution" },
];

const PARTIES = [
  {
    id: "national",
    name: "National",
    short: "NAT",
    leader: "Christopher Luxon",
    role: "Prime Minister",
    color: "#00529F",
    blurb: "Centre-right. Tax relief, fiscal restraint, and getting NZ back on track economically.",
    policyUrl: "https://www.national.org.nz/plan",
  },
  {
    id: "labour",
    name: "Labour",
    short: "LAB",
    leader: "Chris Hipkins",
    role: "Leader of the Opposition",
    color: "#D01C2A",
    blurb: "Centre-left. Public services, wages and workers rights, targeted cost-of-living support.",
    policyUrl: "https://www.labour.org.nz/our-policies/",
  },
  {
    id: "green",
    name: "Green",
    short: "GRN",
    leader: "Co-leaders",
    role: "Green Party",
    color: "#098137",
    blurb: "Progressive and environmental. Climate action, wealth tax, income guarantee.",
    policyUrl: "https://2026-nzgreens.nationbuilder.com/policy",
  },
  {
    id: "act",
    name: "ACT",
    short: "ACT",
    leader: "David Seymour",
    role: "ACT New Zealand",
    color: "#FFD100",
    blurb: "Classical liberal. Smaller government, deregulation, personal responsibility.",
    policyUrl: "https://www.act.org.nz/policies",
  },
  {
    id: "nzfirst",
    name: "NZ First",
    short: "NZF",
    leader: "Winston Peters",
    role: "New Zealand First",
    color: "#000000",
    blurb: "Populist and nationalist. Sovereignty, tighter immigration, law and order.",
    policyUrl: "https://www.nzfirst.nz/news",
  },
  {
    id: "maori",
    name: "Te Pati Maori",
    short: "TPM",
    leader: "Co-leaders",
    role: "Te Pati Maori",
    color: "#9C1C1C",
    blurb: "Indigenous rights. Tino rangatiratanga, Treaty-led policy, rangatahi wellbeing.",
    policyUrl: "https://www.maoriparty.org.nz/policy",
  },
  {
    id: "top",
    name: "The Opportunity Party",
    short: "TOP",
    leader: "Qiulae Wong",
    role: "TOP",
    color: "#17A5A0",
    blurb: "Evidence-based and technocratic. Tax reform, Universal Basic Income, polling near the 5% threshold.",
    policyUrl: "https://www.opportunity.org.nz/policy",
  },
];

/* policies[partyId][domainId] = short simplified summary */
const POLICIES = {
  national: {
    tax: "Ongoing income-tax bracket adjustments for back-pocket relief; restrain government spending growth.",
    housing: "Speed up consenting and land supply via RMA reform; keep interest deductibility for landlords.",
    health: "More frontline staff and shorter wait times; tighter targets for hospitals and cancer treatment.",
    education: "Back-to-basics literacy and numeracy, structured teaching, charter-style school options.",
    climate: "Keep Paris targets but prioritise an affordable transition; more gas exploration allowed.",
    energy: "Lift the offshore oil and gas exploration ban; grow renewables alongside fossil fuel supply security.",
    immigration: "Skills-based settings tied to labour shortages; faster visa processing for key sectors.",
    justice: "Tougher sentencing, more police numbers, boot-camp style youth justice interventions.",
    welfare: "Tighter work obligations and sanctions for jobseekers; targeted rather than universal support.",
    treaty: "Treaty principles handled through existing settlements process; cautious on co-governance expansion.",
    transport: "Roads of national significance, highway and motorway investment prioritised over rail and light rail.",
    foreign: "Traditional Five Eyes alignment; incremental defence spending increases.",
    agriculture: "Ease environmental compliance costs on farmers; delay or soften agricultural emissions pricing.",
    democracy: "No major constitutional change proposed; status-quo electoral settings.",
  },
  labour: {
    tax: "Targeted relief, such as removing GST from fruit and vegetables; resist broad income-tax cuts seen as unaffordable.",
    housing: "Public and social housing build programme; warmer, healthier rental standards enforcement.",
    health: "Reinvest in Health NZ staffing and capacity; reduce reliance on private surgical outsourcing.",
    education: "Smaller class sizes, more learning support staff, pay equity for teachers.",
    climate: "Keep the Emissions Trading Scheme strong; support transition funding for workers and industry.",
    energy: "Retain restrictions on new offshore exploration; accelerate renewable generation and grid upgrades.",
    immigration: "Balance skills needs with migrant worker protections; crack down on exploitation.",
    justice: "Investment in prevention and rehabilitation alongside enforcement; youth justice focus on root causes.",
    welfare: "Lift core benefit rates in line with wages; reduce a sanctions-first approach.",
    treaty: "Support continued Treaty settlements and co-governance arrangements where agreed.",
    transport: "Public transport and rail investment, including light rail and rail network renewal, alongside roading.",
    foreign: "Independent foreign policy within Five Eyes and Pacific partnerships; nuclear-free stance maintained.",
    agriculture: "Phase in agricultural emissions pricing with sector consultation and support packages.",
    democracy: "Open to MMP refinements, such as coalition agreement transparency; no major overhaul proposed.",
  },
  green: {
    tax: "Introduce a wealth and capital tax on high net worth; fund a universal Income Guarantee.",
    housing: "Large-scale public housing build; rent controls and tenancy protections strengthened.",
    health: "Fully public, free-at-point-of-care health system; dental care added to public coverage.",
    education: "Free early childhood education; well-resourced, fully public schooling with no charter schools.",
    climate: "Fastest decarbonisation timeline of major parties; end new fossil fuel exploration immediately.",
    energy: "Rapid shift to 100% renewable electricity; no new oil, gas or coal projects.",
    immigration: "More pathways to residency for migrant workers; stronger protections against exploitation.",
    justice: "Reduce prison population via rehabilitation and addiction and mental-health investment over punishment.",
    welfare: "Universal Income Guarantee ensuring a liveable income floor regardless of work status.",
    treaty: "Strong support for co-governance and Te Tiriti-based partnership across government.",
    transport: "Heavy investment in public and active transport such as buses, rail and cycling; road-building scaled back.",
    foreign: "Nuclear-free, demilitarised foreign policy; emphasis on climate diplomacy in the Pacific.",
    agriculture: "Full agricultural emissions pricing with support for regenerative, lower-emission farming.",
    democracy: "Lower the voting age to 16; campaign finance and lobbying transparency reform.",
  },
  act: {
    tax: "Simplify and cut income tax across the board; cap government spending growth by law.",
    housing: "Deregulate land use, ending urban growth boundaries, so supply can respond to demand.",
    health: "More private-sector contracting and patient choice; competitive provision within public funding.",
    education: "Charter schools expanded; school choice and per-pupil funding that follows the student.",
    climate: "Meet international obligations at least cost; sceptical of subsidy-heavy climate spending.",
    energy: "Open up oil, gas and mineral exploration; remove green tape seen as blocking investment.",
    immigration: "Points-based system favouring high-skill migrants; reduce low-skill visa categories.",
    justice: "Three-strikes style sentencing, victim-focused justice, reduced judicial discretion for repeat offenders.",
    welfare: "Time-limited benefits with strict work-testing; reduce dependency through obligations.",
    treaty: "One law for all citizens; opposes co-governance based on race, wants a public referendum on Treaty principles.",
    transport: "User-pays roading, such as tolls and congestion charging, to fund new highway capacity.",
    foreign: "Strong Five Eyes alignment; supports increased defence spending.",
    agriculture: "Remove agricultural emissions pricing entirely; cut compliance costs for farmers.",
    democracy: "Binding referenda on constitutional questions such as Treaty principles; smaller Parliament debate.",
  },
  nzfirst: {
    tax: "Tax relief targeted at ordinary working families and superannuitants; protect NZ Super entitlements.",
    housing: "Crack down on foreign ownership of housing; support first-home buyers with local-first policies.",
    health: "Protect regional and provincial hospital services; resist centralisation under Health NZ.",
    education: "Return to traditional curriculum and discipline standards; scrutiny of ideological content in schools.",
    climate: "Sceptical of aggressive climate targets if they raise costs; wants a pragmatic, commonsense approach.",
    energy: "Strong support for reopening oil and gas exploration and mining for economic growth.",
    immigration: "Significantly tighter immigration numbers; prioritise New Zealanders for jobs and housing.",
    justice: "Zero-tolerance policing, gang patch bans, tougher penalties for violent and repeat crime.",
    welfare: "Firm work obligations; targeted support for seniors and veterans prioritised.",
    treaty: "Opposes co-governance and separate Maori wards or seats as division by race; one-person-one-vote emphasis.",
    transport: "Support regional roading and infrastructure outside the main cities.",
    foreign: "Strong sovereignty focus; sceptical of international bodies limiting NZ decision-making.",
    agriculture: "Strongly opposes agricultural emissions pricing; backs farmers against city-based regulation.",
    democracy: "Binding referenda on contentious issues such as Treaty principles and co-governance.",
  },
  maori: {
    tax: "Tax the wealthy and corporates more; remove GST from basic kai, meaning food, to ease cost of living.",
    housing: "Maori-led housing papakainga developments; address overcrowding and homelessness in Maori communities.",
    health: "Establish or restore a dedicated Maori health authority; address health inequities directly.",
    education: "Expand kura kaupapa Maori and te reo Maori teaching across the system; Maori curriculum self-determination.",
    climate: "Climate action grounded in kaitiakitanga, meaning guardianship; iwi-led environmental management.",
    energy: "Iwi partnership and benefit-sharing in resource and energy projects on whenua Maori, meaning Maori land.",
    immigration: "Support migration policy that does not undercut Maori employment and wages.",
    justice: "Address disproportionate Maori incarceration; rangatahi-focused rehabilitation over punishment.",
    welfare: "Raise benefit levels; remove punitive sanctions disproportionately affecting Maori whanau.",
    treaty: "Full implementation of Te Tiriti o Waitangi and tino rangatiratanga, meaning self-determination, across government.",
    transport: "Infrastructure investment prioritised for underserved rural and Maori communities.",
    foreign: "Indigenous rights and Pacific solidarity at the centre of foreign policy.",
    agriculture: "Support Maori agribusiness and land return; sustainable, iwi-led land use.",
    democracy: "Permanent dedicated Maori seats and representation; lower voting age to 16.",
  },
  top: {
    tax: "Replace complexity with a simpler system; tax income from assets like housing the same as wages.",
    housing: "Tax capital gains and land to cool speculation; use revenue to lower income tax, boosting supply indirectly.",
    health: "Invest in primary and preventative care to cut pressure on hospitals; data-driven targets.",
    education: "Evidence-based teaching methods; better pay progression tied to skills, not just tenure.",
    climate: "Technology and price-based decarbonisation via carbon pricing over picking winners with subsidies.",
    energy: "Support renewables expansion via market mechanisms; open to nuclear and advanced-tech debate.",
    immigration: "Points-based system with regular review tied to actual economic evidence, not politics.",
    justice: "Investment in programmes shown by data to reduce reoffending; sentencing guided by evidence.",
    welfare: "Introduce a Universal Basic Income, an unconditional base payment, replacing parts of the current system.",
    treaty: "Supports Treaty obligations being met but wants clearer, evidence-based processes.",
    transport: "Congestion pricing to fund infrastructure efficiently; mode-neutral investment decisions.",
    foreign: "Pragmatic, trade- and evidence-focused foreign policy.",
    agriculture: "Market-based emissions pricing for agriculture, phased in with the sector.",
    democracy: "Push for MMP refinements and more transparent, evidence-based policymaking.",
  },
};

/* Also on the ballot - other registered parties not in the main 7.
   Headline pitch only; not all have published full manifestos. */
const OTHER_PARTIES = [
  { name: "New Conservatives", pitch: "Socially conservative values, lower taxes, and family-focused policy." },
  { name: "Freedoms NZ", pitch: "Civil liberties, medical freedom, and opposition to pandemic-era mandates." },
  { name: "NZ Loyal", pitch: "Anti-establishment, sovereignty and a Kiwi-first platform." },
  { name: "Democracy NZ", pitch: "Direct democracy via binding citizen-initiated referenda." },
  { name: "Heartland New Zealand", pitch: "Rural and regional communities, provincial economic revival." },
  { name: "Outdoors and Freedom Party", pitch: "Hunting, fishing and outdoor recreation access rights." },
  { name: "Legalise Cannabis Party", pitch: "Cannabis law reform and drug policy decriminalisation." },
  { name: "Animal Justice Party", pitch: "Animal welfare law reform and ending animal farming subsidies." },
  { name: "Womens Rights Party", pitch: "Single-issue focus on sex-based rights and protections." },
  { name: "Vision NZ", pitch: "Faith-based values platform with a focus on family and community." },
];

/* Developing movements / news ticker - static snapshot as supplied */
const NEWS_ITEMS = [
  { date: "12 Aug 2026", text: "PM Christopher Luxon survived a second National Party leadership vote, keeping the current coalition leadership intact heading into the campaign." },
  { date: "Aug-Sep 2026", text: "The Opportunity Party polling crept toward the 5% threshold for the first time, putting a possible 7th party in Parliament in play." },
  { date: "4-11 Sep 2026", text: "The Post/Freshwater Strategy poll had Labour on 28% narrowly ahead of National on 27%, with the Greens on 14% - the race remains tight." },
  { date: "16 Sep 2026", text: "A Health Coalition Aotearoa survey found Greens, Te Pati Maori and Labour giving the strongest backing to tougher tobacco and alcohol prevention rules." },
];
